import LogoWETH from 'assets/images/token/LogoWETH.png'
import { tokenAddressMap} from './tokenAddressMap'

const auroraTokens:Array<any> = [
    { 
        name: 'AETH1',
        buyerCoinAddress: tokenAddressMap['AETH1'],
        productTitle: 'AETH1-Pool',
        productEpoch: 'Epoch 1',
        logoUrl: LogoWETH,
        pid: 0,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'ayDAI',
        symbolB: 'byDAI',
        aTrancheAddress: '0x3DfaF77C48dE53E867AeB2fCBb5Ecc08703DE854',
        bTrancheAddress: '0x876115F0Fc769be87d7C50C063a4286Fb7457588',
        isEarningsEnd: false, // 收益是否结束 true为结束
    },
    { 
        name: 'AETH2',
        buyerCoinAddress: tokenAddressMap['AETH2'],
        productTitle: 'AETH2-Pool',
        productEpoch: 'Epoch 2',
        logoUrl: LogoWETH,
        pid: 1,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'ayDAI',
        symbolB: 'byDAI',
        aTrancheAddress: '0x8C6cbF014262b97e0C59791F9b706aAAA72B5491',
        bTrancheAddress: '0xccDb3A7300af15110805C4E88f4186f31433BCA1',
        isEarningsEnd: false, // 收益是否结束 true为结束
    },
    { 
        name: 'AETH3',
        buyerCoinAddress: tokenAddressMap['AETH3'],
        productTitle: 'AETH3-Pool',
        productEpoch: 'Epoch 3',
        logoUrl: LogoWETH,
        pid: 2,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'ayDAI',
        symbolB: 'byDAI',
        aTrancheAddress: '0x2B6682893AEc86caBe657a2954CF6Eb2E9C2B419',
        bTrancheAddress: '0xD2EAC03738677D4c802e6eb902Ede1ce526c61A1',
        isEarningsEnd: false, // 收益是否结束 true为结束
    },

    { 
        name: 'AETH4',
        buyerCoinAddress: tokenAddressMap['AETH4'],
        productTitle: 'AETH4-Pool',
        productEpoch: 'Epoch 4',
        logoUrl: LogoWETH,
        pid: 3,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'ayDAI',
        symbolB: 'byDAI',
        aTrancheAddress: '0x1E27cC5833F3Ba4Ee76c435Ee0081c88B364C936',
        bTrancheAddress: '0xdeF83479778386F7471E24F218952D23C9A6176C',
        isEarningsEnd: false, // 收益是否结束 true为结束
    },

    { 
        name: 'AETH5',
        buyerCoinAddress: tokenAddressMap['AETH5'],
        productTitle: 'AETH5-Pool',
        productEpoch: 'Epoch 5',
        logoUrl: LogoWETH,
        pid: 4,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'ayDAI',
        symbolB: 'byDAI',
        aTrancheAddress: '0xF30A4d0786130c1B04C41598307a3fFd4792079e',
        bTrancheAddress: '0x8901328B1EDD3eE3A19Ed5efc6EB5Ebe97b0655d',
        isEarningsEnd: false, // 收益是否结束 true为结束
    },
    { 
        name: 'AETH6',
        buyerCoinAddress: tokenAddressMap['AETH6'],
        productTitle: 'AETH6-Pool',
        productEpoch: 'Epoch 6',
        logoUrl: LogoWETH,
        pid: 5,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'ayDAI',
        symbolB: 'byDAI',
        aTrancheAddress: '0x3b152877BC53E5774C28d62bB6D432b6c0127eA7',
        bTrancheAddress: '0xFB66eD2d96dfc4DC4f0951930817BE21E8c5e2A6',
        isEarningsEnd: false, // 收益是否结束 true为结束
    },
    { 
        name: 'AETH7',
        buyerCoinAddress: tokenAddressMap['AETH7'],
        productTitle: 'AETH7-Pool',
        productEpoch: 'Epoch 7',
        logoUrl: LogoWETH,
        pid: 6,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'ayDAI',
        symbolB: 'byDAI',
        aTrancheAddress: '0x664fa42d0431c5B98F73D7dC2f3040Fb91B81903',
        bTrancheAddress: '0x59d2B1FA326F01530F9541cb7765485536eA5705',
        isEarningsEnd: false, // 收益是否结束 true为结束
    },
    { 
        name: 'AETH8',
        buyerCoinAddress: tokenAddressMap['AETH8'],
        productTitle: 'AETH8-Pool',
        productEpoch: 'Epoch 8',
        logoUrl: LogoWETH,
        pid: 7,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'ayDAI',
        symbolB: 'byDAI',
        aTrancheAddress: '0xb5518c2cD20e4A2987C8d9675D8270916d3B83e4',
        bTrancheAddress: '0x020446b0438c592Fa37A9e28eD8bB8c9F3Cd9F5C',
        isEarningsEnd: false, // 收益是否结束 true为结束
    },
    { 
        name: 'AETH9',
        buyerCoinAddress: tokenAddressMap['AETH9'],
        productTitle: 'AETH9-Pool',
        productEpoch: 'Epoch 9',
        logoUrl: LogoWETH,
        pid: 8,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'ayDAI',
        symbolB: 'byDAI',
        aTrancheAddress: '0x982659717185D60e996dCF9908A2fab538b2FC64',
        bTrancheAddress: '0x427CD7e773dC8E02595737Da91871405AaeBe176',
        isEarningsEnd: false, // 收益是否结束 true为结束
    },
    { 
        name: 'AETH10',
        buyerCoinAddress: tokenAddressMap['AETH10'],
        productTitle: 'AETH10-Pool',
        productEpoch: 'Epoch 10',
        logoUrl: LogoWETH,
        pid: 10,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'ayDAI',
        symbolB: 'byDAI',
        aTrancheAddress: '0x7fd4981D736Ecaa9481DbC38a32e84B74F381e03',
        bTrancheAddress: '0xdb5C2117f84be039315FB152bc7e0e42f15F69D8',
        isEarningsEnd: false, // 收益是否结束 true为结束
    },
    { 
        name: 'AETH11',
        buyerCoinAddress: tokenAddressMap['AETH11'],
        productTitle: 'AETH11-Pool',
        productEpoch: 'Epoch 11',
        logoUrl: LogoWETH,
        pid: 11,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'ayDAI',
        symbolB: 'byDAI',
        aTrancheAddress: '0x17a7B2aF26ec943B2233e5Af14134B6408202af4',
        bTrancheAddress: '0x203Db7a0651558C7B3877CB440A1e1Bb82728D0B',
        isEarningsEnd: false, // 收益是否结束 true为结束
    },
]

export default auroraTokens