import LogoUSDT from 'assets/images/token/LogoUSDT.png'
import LogoWETH from 'assets/images/token/LogoWETH.png'
import LogoDAI from 'assets/images/token/LogoDAI.png'
import { tokenAddressMap} from './tokenAddressMap'

const polygonTokens:Array<any> = [
    { 
        name: 'WETH',
        buyerCoinAddress: '0x0B65C393A62EA314FE438d47E69d35D3AACb511D',
        productTitle: 'WETH-1Pool',
        productEpoch: 'Epoch 1',
        logoUrl: LogoWETH,
        pid: 0,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'ayDAI',
        symbolB: 'byDAI',
        aTrancheAddress: '0xf289FD909084f55FA00EdfB9C556214B183fa67d',
        bTrancheAddress: '0x2D747d03a55d63efaf7b794FBfd66A97B73F41B4',
        isEarningsEnd: false, // 收益是否结束 true为结束
    },
    { 
        name: 'USDT',
        buyerCoinAddress: tokenAddressMap['USDT'],
        productTitle: 'USDT-2Pool',
        productEpoch: 'Epoch 1',
        logoUrl: LogoUSDT,
        pid: 1,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'aT',
        symbolB: 'bT',
        aTrancheAddress: '0xC8c3af0c1AE16FB356CEc4934E79eeA1Fb6e5aEB',
        bTrancheAddress: '0x496b979f97C06f504631D73E4e2b9B404a14bb91',
        isEarningsEnd: false,
    },
    { 
        name: 'DAI',
        buyerCoinAddress: '',
        productTitle: 'DAI-3Pool',
        productEpoch: 'Epoch 1',
        logoUrl: LogoDAI,
        pid: 2,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'aaDAI',
        symbolB: 'bbDAI',
        aTrancheAddress: '0x7517CbF9567865eac6174cE6fFcDfE8810fbcCbB',
        bTrancheAddress: '0x6BCae915484ec3b7b6a8A0082290005cE225b654',
        isEarningsEnd: false,
    },
    { 
        name: 'WETH',
        buyerCoinAddress: tokenAddressMap['WETH'],
        productTitle: 'WETH-4Pool',
        productEpoch: 'Epoch 1',
        logoUrl: LogoWETH,
        pid: 3,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'aa4BTC',
        symbolB: 'bb4BTC',
        aTrancheAddress: '0x68dB841523d431277828b94B6BFcA41c5EAf35Dd',
        bTrancheAddress: '0x887e4441F5A9BF2f83b7E33dfFd0191790582c05',
        isEarningsEnd: false,
    },
    { 
        name: 'WETH',
        buyerCoinAddress: tokenAddressMap['WETH'],
        productTitle: 'WETH-5Pool',
        productEpoch: 'Epoch 2',
        logoUrl: LogoWETH,
        pid: 4,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'aa5BTC',
        symbolB: 'bb5BTC',
        aTrancheAddress: '0xBBaD4a914178f30C13371754197b4c1FD72552df',
        bTrancheAddress: '0x5d40FF9ABb5c19df29A332Bf2aa3D65A29143bb7',
        isEarningsEnd: false,
    },
    { 
        name: 'WETH',
        buyerCoinAddress: tokenAddressMap['WETH'],
        productTitle: 'WETH-6Pool',
        productEpoch: 'Epoch 3',
        logoUrl: LogoWETH,
        pid: 5,
        fixedStatus: 'Incoming',
        variableStatus: 'Incoming',
        fixedApy: 0,
        variableApy: 0,
        symbolADepositedBalance: 0,
        symbolBDepositedBalance: 0,
        symbolA: 'aa6BTC',
        symbolB: 'bb6BTC',
        aTrancheAddress: '0x759B7C0Fc8D70C0987F93c827E2A1AE02E63a5CA',
        bTrancheAddress: '0xb1Bf674ef586C0750496B4C1299e43766f22Bbf1',
        isEarningsEnd: false,
    },
]

export default polygonTokens